ft-navbar completed
sirkudos/movie-database pull request #3
Opened 2022-01-25 23:47 UTC by sirkudos

ft-navigation bar completed

2022-01-26 00:41 UTC, sirkudos commented
#### What does this PR do?
  - It is a navigation bar with search input.
#### Description of Task to be completed?
 - Searching of movies, and also loging In 
#### How should this be manually tested?
 - npm start
#### Any background context you want to provide?
  - N/A
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/33374376/151083497-1fdb1bce-cb56-4e24-b805-db490885a0af.png)

2022-01-26 01:05 UTC, chrismeeky requested changes

2022-01-26 01:05 UTC, chrismeeky commented on src/App.js
>      <div className="App">
Consider taking away this div wrapper

2022-01-26 01:05 UTC, chrismeeky commented on src/App.js
> +      <NavBar />
NavBar should be a child component of a Home component. I think it is better to have a Home component here rather than a Navbar. The Navbar component should then be rendered inside the Home component

2022-01-26 01:05 UTC, chrismeeky commented on src/components/navbar/NavBar.jsx
> +    <div className="navBar">
You might consider using the Nav element instead of div (line 10) as Nav is more semantic

2022-01-26 01:05 UTC, chrismeeky commented on src/components/navbar/NavBar.jsx
> +      <div className="navBar__container">
Are you sure you need this extra div ? Don't you think the Outermost element (on line 10) is enough to serve as the container ?

2022-01-26 01:05 UTC, chrismeeky commented on src/components/navbar/navBar.scss
> +    &__container {
If you remove the div with this class name from the JSX, you might not be needing this styling. Consider removing this container from the JSX and move the style in this block up inside the navBar

2022-01-26 01:05 UTC, chrismeeky commented on src/components/navbar/navBar.scss
> +.navBar {
it is more conventional write class names in kebab-case (nav-bar) than camelCase (navBar)

2022-01-26 01:05 UTC, chrismeeky commented on src/components/navbar/NavBar.jsx
> +        <div className="navBar__rightSide">
nav-bar__right is a better class name

2022-01-27 17:51 UTC, sirkudos commented on src/App.js
>      <div className="App">
Implemented

2022-01-27 17:53 UTC, sirkudos commented on src/components/navbar/NavBar.jsx
> +    <div className="navBar">
Implemented

2022-01-27 18:11 UTC, sirkudos commented on src/components/navbar/NavBar.jsx
> +      <div className="navBar__container">
Implemented

2022-01-27 18:12 UTC, sirkudos commented on src/components/navbar/navBar.scss
> +    &__container {
Done

2022-01-27 18:16 UTC, sirkudos commented on src/components/navbar/NavBar.jsx
> +        <div className="navBar__rightSide">
implemented

2022-01-27 19:49 UTC, merged